# Generated by Django 5.2 on 2025-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='SMS_sent',
            field=models.BooleanField(default=False, verbose_name='پیامک داده شده'),
        ),
    ]
